### ISSUE TITLE
please fix non UTF-8 surrogateescapes

### ISSUE THREAD

**Issue by x0day** [elastic/elasticsearch-py-async#62]
It's already fixed in elasticsearch-py, but not in elasticsearch-py-async.

https://github.com/elastic/elasticsearch-py/issues/611
https://github.com/elastic/elasticsearch-py/pull/612
https://github.com/elastic/elasticsearch-py-async/blob/master/elasticsearch_async/transport.py#L201

**Comment by x0day** [comment]
also should be fixed in response.

https://github.com/elastic/elasticsearch-py-async/blob/fe0e6d6c4065ea191384fb1cd4ac08a72162cc80/elasticsearch_async/connection.py#L99

changes to

```
raw_data = yield from response.content() 
raw_data = raw_data.decode('utf-8', errors='surrogatepass')
```

**Comment by johnchenghk01** [comment]
https://github.com/elastic/elasticsearch-py/blob/1fa6cb8c40828f3035029a5873db3d2a36e78813/elasticsearch/helpers/actions.py#L85
Not fixed in helpers.

**Comment by sethmlarson** [comment]
This is fixed in `elasticsearch[async]` 7.8.0, see https://github.com/elastic/elasticsearch-py-async/issues/81 for more information.
